# Generated by Django 3.2.5 on 2021-07-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerDashboard', '0002_remove_playerbio_aflawards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerbio',
            name='bio',
        ),
    ]
