# Generated by Django 3.2.5 on 2021-07-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerDashboard', '0003_remove_playerbio_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbio',
            name='debutYear',
            field=models.CharField(max_length=200),
        ),
    ]
