# Generated by Django 3.2.5 on 2021-07-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerDashboard', '0004_alter_playerbio_debutyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbio',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerbio',
            name='draftPosition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerbio',
            name='heightCm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerbio',
            name='jumperNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerbio',
            name='weightKg',
            field=models.IntegerField(default=0),
        ),
    ]
