# Generated by Django 3.2.5 on 2021-07-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerDashboard', '0006_auto_20210727_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayerDashboard.player')),
                ('playerStats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayerDashboard.playerstats')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='PlayerDashboard.PlayerGameStats'),
        ),
    ]
